### ISSUE TITLE
IRCv3 support

### ISSUE THREAD

**Issue by nyuszika7h** [caffeinery/coffea#33]
# [IRCv3.1](http://ircv3.net/irc/3.1.html)

## Base Extensions

- [x] [Capability Negotiation](http://ircv3.net/specs/core/capability-negotiation-3.1.html)
- [ ] [`multi-prefix` Extension](http://ircv3.net/specs/extensions/multi-prefix-3.1.html)
- [x] [`sasl` Extension](http://ircv3.net/specs/extensions/sasl-3.1.html)

## Optional Extensions

- [x] [`account-notify` Extension](http://ircv3.net/specs/extensions/account-notify-3.1.html)
- [x] [`away-notify` Extension](http://ircv3.net/specs/extensions/away-notify-3.1.html)
- [x] [`extended-join` Extension](http://ircv3.net/specs/extensions/extended-join-3.1.html)
- [ ] [`tls` Extension](http://ircv3.net/specs/extensions/tls-3.1.html)

# [IRCv3.2](http://ircv3.net/irc/3.2.html)

## Base Extensions

- [ ] [Capability Negotiation](http://ircv3.net/specs/core/capability-negotiation-3.2.html) **(updated)**
- [x] [Message Tags](http://ircv3.net/specs/core/message-tags-3.2.html)
- [ ] [`metadata` Extension](http://ircv3.net/specs/core/metadata-3.2.html)
- [ ] [`monitor` Extension](http://ircv3.net/specs/core/monitor-3.2.html)

## Optional Extensions

- [ ] [`account-tag` Extension](http://ircv3.net/specs/extensions/account-tag-3.2.html)
- [ ] [`batch` Extension](http://ircv3.net/specs/extensions/batch-3.2.html)
- [ ] [`cap-notify` Extension](http://ircv3.net/specs/extensions/cap-notify-3.2.html)
- [ ] [`chghost` Extension](http://ircv3.net/specs/extensions/chghost-3.2.html)
- [ ] [`echo-message` Extension](http://ircv3.net/specs/extensions/echo-message-3.2.html)
- [ ] [`invite-notify` Extension](http://ircv3.net/specs/extensions/invite-notify-3.2.html)
- [ ] [`sasl` Extension](http://ircv3.net/specs/extensions/sasl-3.2.html) **(updated)**
- [ ] [`server-time` Extension](http://ircv3.net/specs/extensions/server-time-3.2.html)
- [ ] [`userhost-in-names` Extension](http://ircv3.net/specs/extensions/userhost-in-names-3.2.html)

# SASL Mechanisms

- [ ] [`PLAIN`](https://tools.ietf.org/search/rfc4616) as defined by RFC 4616
- [ ] [`EXTERNAL`](https://tools.ietf.org/html/rfc4422#appendix-A) as defined by RFC 4422
- [ ] [`ECDSA-NIST256P-CHALLENGE`](https://github.com/kaniini/ecdsatool) (supported by at least  charybdis, ircd-seven (freenode))
- [ ] [`SCRAM-SHA-256`](https://tools.ietf.org/html/draft-hansen-scram-sha256-02) **(draft)** (not supported anywhere yet AFAIK)

**Comment by omnidan** [comment]
Closing this here for now. This should be considered in coffea-irc, though: caffeinery/coffea-irc#2
