### ISSUE TITLE
make plugin loader resursive

### ISSUE THREAD

**Issue by michealharker** [caffeinery/coffea#37]
i want to see a better folder structure in plugins/ or lib/ so yeah

**Comment by omnidan** [comment]
This works in the [`plugin-manager` branch](https://github.com/caffeinery/coffea/tree/plugin-manager) - but make sure to read https://github.com/caffeinery/coffea/issues/19#issuecomment-127360910 as there are still some issues with that branch.

Use `client.loadPlugins(path)` to load all plugins (`.js` files) recursively from the specified path and subdirectories. [The irc protocol already loads all of `lib/irc/plugins/` recursively.](https://github.com/caffeinery/coffea/blob/plugin-manager/lib/irc/index.js#L192)
