### ISSUE TITLE
We should document OOP plugins for great good.

### ISSUE THREAD

**Issue by terinjokes** [caffeinery/coffea#53]
I'm using `hypermq` bound on localhost using the chit/chat patten. I listen for coffea's `message` event, and pass the channel name, the user's name and the message to the OOP plugins. I listen for messages back from hypermq, and pass along the relevant details to the send method.

This allows for plugins which respond biased on some user input in addition to plugins which broadcast to a channel, with no modifications needed to the process connected to the IRC network. Additionally, allows the plugins to be upgraded and restarted without any downtime for the IRC bot.

**Comment by omnidan** [comment]
@terinjokes we have https://coffea.caffeinery.org/ for documentation now, not sure if that helps with your issue as I've never worked with `hypermq` (just checked and seems like it's deprecated by `securemq` now). Or did you just mean documenting the process that you are using? It sounds interesting, although I'm really not familiar with this.

**Comment by omnidan** [comment]
Irrelevant from [0.6](https://github.com/caffeinery/coffea/tree/0.6) on.
