### ISSUE TITLE
Add connect event and maybe other core events

### ISSUE THREAD

**Issue by omnidan** [caffeinery/coffea#57]
connect after motd or after connection?

After connection you might not be able to send JOIN and other commands yet (?)

- [x] `connect` event
- [x] numeric events such as `005` or just `numeric` with data.

**Comment by michealharker** [comment]
connect, disconnect (prehaps?) - could also think about sending numerics as events, for example 005. In addition,

**Comment by michealharker** [comment]
I added the connect event in `5cec000`

**Comment by michealharker** [comment]
Implemented numerics in 06032bf
