### ISSUE TITLE
Auto-rejoin on kick (and other small, useful features?)

### ISSUE THREAD

**Issue by omnidan** [caffeinery/coffea#61]
Please leave suggestions for other useful features here.

**Comment by zackp30** [comment]
Auto-rejoin on kick should be an extension IMO.

**Comment by omnidan** [comment]
I agree @zackp30 - I already mentioned on IRC that I've been thinking if features like this should be part of the core or an extension (like in express, then you could do `client.use(require('coffea-kickrejoin')`). I'm moving this to 0.5 then as that's when we start working on the (new) plugin system.

**Comment by zackp30** [comment]
Alright. :smile:

**Comment by omnidan** [comment]
This is possible now and there already is the [`coffea-telegram` plugin](https://github.com/caffeinery/coffea-telegram). Implementing an auto-rejoin plugin shouldn't be too hard now.

I'll close this issue but if anyone has plugin ideas please collect them here.
