### ISSUE TITLE
Send periodic PINGs to the server to detect ping timeout

### ISSUE THREAD

**Issue by nyuszika7h** [caffeinery/coffea#63]
If the bot disconnects uncleanly (e.g. ping timeout), it might not notice it, and if it isn't writing to the socket, chances are it will never notice it. As soon as it tries to write to the socket, it would get a "Broken pipe" error.

To avoid this issue, coffea should send periodic keepalive `PING`s to the server. (The interval should be probably configurable.)

**Comment by omnidan** [comment]
@nyuszika7h could you post the crash logs, maybe a short reproduction log (including ircd information and what you did to produce the crash)? I haven't had problems with any ircds yet.

**Comment by michealharker** [comment]
I was going to work on this, then I realised we have a way of detecteting that we've disconnected: The socket closes/ends. Why it wouldn't close the socket when we're disconnected intrigues me. Can this be consistently reproduced?

**Comment by nyuszika7h** [comment]
@omnidan There is no "crash log", as the bot simply stays running, unless something makes it write to the socket.

@michealharker This is not an issue with coffea in particular, it's just how TCP works. If the server doesn't send an RST for whatever reason (could be a dropped packet), the client won't know it's disconnected unless it tries (and fails) to write to the socket.

I can give you a way to reproduce it, though, as a few days ago I discovered that Undernet's ircd does not send any feedback at all on `QUIT`.

**Comment by omnidan** [comment]
Closing this here for now. This should be considered in `coffea-irc`, though: https://github.com/caffeinery/coffea-irc/issues/1
