### ISSUE TITLE
support different chat protocols

### ISSUE THREAD

**Issue by omnidan** [caffeinery/coffea#64]
Planned support for:

 * IRC: Prefix with `irc:` in connection host string, example: `irc:chat.freenode.net`
 * Telegram: Prefix with `telegram:` then pass connection information, example: `telegram:botname`
 * Default (no prefix) will remain IRC for backwards compatibility

**Comment by michealharker** [comment]
If we are doing that we could just add support for "plug-ins" to the core coffea codebase, so if you want some feature you just plug it into the bot somehow

**Comment by omnidan** [comment]
@michealharker okay, I am working on the plugin system right now and will add support for telegram in a separate `coffea-telegram` repo later.

**Comment by omnidan** [comment]
This works in the [`plugin-manager` branch](https://github.com/caffeinery/coffea/tree/plugin-manager) - but make sure to read https://github.com/caffeinery/coffea/issues/19#issuecomment-127360910 as there are still some issues with that branch.
