### ISSUE TITLE
Bug - When connecting to 2 or more networks, only 1 connect is made (last added network)

### ISSUE THREAD

**Issue by tomhatzer** [caffeinery/coffea#76]
Just found another really nasty bug.

When I specify 2 or more networks (with names), the client only connects to the last added network. It looks like all other networks are ignored and only this connection is handled.

After the connect is successful, the client joins the specified channels from all networks on the single connected network. As there would be no other networks.

**Comment by omnidan** [comment]
@tomhatzer can you try out 0.5 and let me know if it works fine there? I'm personally using 0.5 and haven't had this issue. It might have to do with recent additions to 0.4 (`005.js` etc)

**Comment by tomhatzer** [comment]
@omnidan can you guide me to 0.5? The latest version I can see is 0.4.22. THX!

**Comment by tomhatzer** [comment]
Sorry, got the 0.5 (plugin-manager). Gonna test it with that one. Do you have an initial setup for 0.5 that I could test? Looks like there changed quite a few things.

Thanks!

**Comment by tomhatzer** [comment]
@omnidan Sorry for spamming, but I've got another error message with the 0.5 version:

```
coffea/index.js:279
    if (!f) throw new Error("Function '" + name + "' not available in protocol '" + protocol + "'");
            ^

Error: Function 'inspect' not available in protocol 'irc'
    at Client.buildFunction (coffea/index.js:279:19)
    at Client.__noSuchMethod__ (coffea/index.js:308:18)
    at Client.<anonymous> (coffea/methodMissing.js:19:16)
    at formatValue (util.js:205:21)
    at inspect (util.js:105:10)
    at Console.exports.format (util.js:13:20)
    at Console.log (console.js:36:34)
    at Object.<anonymous> (bot.js:34:9)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
```
